src/Entity/Enterprise.php
<?php

namespace App\Entity;

use App\Repository\EnterpriseRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;




 
// Exemples annotations pour une recherche fullText sur les champs business_name,siret_number,zip_code,phone_number et city
//
// @ORM\Table(name="enterprise", indexes={@ORM\Index(columns={"business_name","siret_number","zip_code","phone_number","city"})}, flags={"fulltext"})})



/**
 * @ORM\Entity(repositoryClass=EnterpriseRepository::class)
 */
class Enterprise
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $business_name;

    /**
     * @ORM\Column(type="string",length=255)
     */
    private $siret_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_more;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="decimal", precision=50, scale=10, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", precision=50, scale=10, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contact_mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $created_by;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $updated_by;

    /**
     * @ORM\ManyToMany(targetEntity=Certification::class, inversedBy="enterprises")
     */
    private $certification;

    /**
     * @ORM\OneToOne(targetEntity=User::class,  mappedBy="userEnterprise", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Document::class, mappedBy="enterprise")
     */
    private $documents;

     /**
     * @ORM\OneToMany(targetEntity=Announcement::class, mappedBy="enterprise", cascade={"persist", "remove"})
     */
    private $announcement;

    public function __construct()
    {
        $this->setUpdatedAt(new \DateTimeImmutable('now'));    
        
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTimeImmutable('now'));
        }
        if ($this->getUpdatedAt() === null) {
            $this->setUpdatedAt(new \DateTimeImmutable('now'));
        }
        $this->certification = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->created_at = new DateTimeImmutable();
        $this->announcement = new ArrayCollection();
    }

    public function __toString() 
    {
        return $this->business_name;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBusinessName(): ?string
    {
        return $this->business_name;
    }

    public function setBusinessName(string $business_name): self
    {
        $this->business_name = $business_name;

        return $this;
    }
    
    public function getSiretNumber(): ?string
    {
        return $this->siret_number;
    }

    public function setSiretNumber(string $siret_number): self
    {
        $this->siret_number = $siret_number;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAddressMore(): ?string
    {
        return $this->address_more;
    }

    public function setAddressMore(string $address_more): self
    {
        $this->address_more = $address_more;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(?string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getContactMail(): ?string
    {
        return $this->contact_mail;
    }

    public function setContactMail(string $contact_mail): self
    {
        $this->contact_mail = $contact_mail;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedBy(): ?string
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?string $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }

    /**
     * @return Collection|Certification[]
     */
    public function getCertification(): Collection
    {
        return $this->certification;
    }

    public function addCertification(Certification $certification): self
    {
        if (!$this->certification->contains($certification)) {
            $this->certification[] = $certification;
        }

        return $this;
    }

    public function removeCertification(Certification $certification): self
    {
        $this->certification->removeElement($certification);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->addEnterprise($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            $document->removeEnterprise($this);
        }

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncement(): Collection
    {
        return $this->announcement;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcement->contains($announcement)) {
            $this->announcement[] = $announcement;
            $announcement->setEnterprise($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcement->removeElement($announcement)) {
            // set the owning side to null (unless already changed)
            if ($announcement->getEnterprise() === $this) {
                $announcement->setEnterprise(null);
            }
        }

        return $this;
    }

    

    

    
}

src/Form/BackOffice/EnterpriseType.php
<?php

namespace App\Form\BackOffice;

use App\Entity\Enterprise;
use App\Entity\Announcement;
use App\Entity\Certification;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnterpriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('slug')
            ->add('business_name')
            ->add('siret_number')
            ->add('address')
            ->add('address_more')
            ->add('zip_code')
            ->add('phone_number')
            ->add('logo')
            ->add('latitude')
            ->add('longitude')
            ->add('contact_mail')
            ->add('city')
            // ->add('created_at')
            // ->add('updated_at')
            // ->add('created_by')
            // ->add('updated_by')
            ->add('certification', EntityType::class, [
                'class' => Certification::class,
                'multiple' => true,
                'expanded' => true,
                'choice_label' => 'name',
              
            ])
            //->add('user')
            //->add('documents')
            ->add('announcement', EntityType::class, [
                'class' => Announcement::class,
                'multiple' => true,
                'expanded' => true,
                'choice_label' => 'title',
              
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enterprise::class,
        ]);
    }
}

src/Controller/BackOffice/EnterpriseController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Enterprise;
use App\Form\BackOffice\EnterpriseType;
use App\Repository\EnterpriseRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @Route("/backoffice/enterprise", name="backoffice_enterprise_")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class EnterpriseController extends AbstractController
{

    /**
     * @Route("/", name="browse", methods={"GET"})
     */
    public function browse(EnterpriseRepository $enterpriseRepository): Response
    {

        return $this->render('backoffice/enterprise/browse.html.twig', [
            'enterprise_list' => $enterpriseRepository->findAll()

        ]);
    }

    /**
     * @Route("/{id}/read", name="read", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function read(Enterprise $enterprise): Response
    {

        $enterpriseForm = $this->createForm(EnterpriseType::class, $enterprise, [
            'disabled' => 'disabled'
        ]);

        // on fournit ce formulaire à notre vue
        return $this->render('backoffice/enterprise/read.html.twig', [
            'enterprise_form' => $enterpriseForm->createView(),
            'enterprise' => $enterprise,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, Enterprise $enterprise): Response
    {
        $enterpriseForm = $this->createForm(EnterpriseType::class, $enterprise);

        $enterpriseForm->handleRequest($request);

        if ($enterpriseForm->isSubmitted() && $enterpriseForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $enterprise->setUpdatedAt(new DateTimeImmutable());
            $entityManager->flush();

            $this->addFlash('success', "Enterprise `{$enterprise->getBusinessName()}` udpated successfully");

            return $this->redirectToRoute('backoffice_enterprise_browse');
        }


        return $this->render('backoffice/enterprise/add.html.twig', [
            'enterprise_form' => $enterpriseForm->createView(),
            'enterprise' => $enterprise,
            'page' => 'edit',
        ]);
    }
    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     */
    public function add(Request $request, SluggerInterface $slugger): Response
    {
        $enterprise = new Enterprise();


        $enterpriseForm = $this->createForm(EnterpriseType::class, $enterprise);


        $enterpriseForm->handleRequest($request);


        if ($enterpriseForm->isSubmitted() && $enterpriseForm->isValid()) {

            $enterprise->setSlug(strtolower($slugger->slug($enterprise->getBusinessName())));

            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($enterprise);
            $entityManager->flush();


            $this->addFlash('success', "Enterprise {$enterprise->getBusinessName()} created successfully");


            return $this->redirectToRoute('backoffice_enterprise_browse');
        }


        return $this->render('backoffice/enterprise/add.html.twig', [
            'enterprise_form' => $enterpriseForm->createView(),
            'page' => 'create',
        ]);
    }

    /**
     * @Route("/{id}/delete/", name="delete", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function delete(Enterprise $enterprise, EntityManagerInterface $entityManager): Response
    {
        $this->addFlash('success', "Enterprise {$enterprise->getBusinessName()} deleted");

        $entityManager->remove($enterprise);
        $entityManager->flush();

        return $this->redirectToRoute('backoffice_enterprise_browse');
    }
}

templates/enterprise/add.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<br>
<br>
<br>
	
	<div class="container">

		{{ form_start(enterprise_form) }}

		{{ form_errors(enterprise_form) }}
        
		{{ form_row(enterprise_form.business_name) }}
		{{ form_row(enterprise_form.logo) }}
		{{ form_row(enterprise_form.siret_number) }}
		{{ form_row(enterprise_form.address) }}
		{{ form_row(enterprise_form.address_more) }}
		{{ form_row(enterprise_form.city) }}
		{{ form_row(enterprise_form.zip_code) }}
		{{ form_row(enterprise_form.phone_number) }}
		{{ form_row(enterprise_form.contact_mail) }}
		
		

		<button type="submit" class="btn btn-primary mt-4">
		Modifier
    </button>
		{{ form_end(enterprise_form) }}
	</div>
{% endblock %}

templates/enterprise/browse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises
{% endblock %}

{% block body %}
	<main>

		<section class="py-5 text-center container mt-">
			<div class="d-flex py-lg-5">
				<div class="mx-auto">
					<h1 class="fw-bold text-start">Trouvez des experts proches de chez vous</h1>
				</div>
			</div>
		</section>

		<section class="py-5 text-center container mt-">
			<div class="d-flex" id="home-register">
				<div class="col-lg-6 col-md-8 " id="home-register-left">

					<form class="d-flex flex-column flex-md-row" method="GET">
						<input name="searchEnterprise" class="form-control me-2" type="search" placeholder="Entrez le nom de la ville (exemple : Paris)" aria-label="Search">
						<button class="btn btn-outline-primary mt-2 mt-md-0" type="submit">Rechercher</button>
					</form>

				</div>
			</div>
		</section>

		<div class="album py-5 bg-light">
			<div class="container">

				<div class="row">
					<div class="col">

						{% if search_form != null %}
							<div class="shadow-sm card p-4" id="enterprises-result">
								<h4 class="text-center">Liste des experts dans la ville de :
									{{ search_form }}</h4>
								<div class="container h-100">
									<div class="row h-100">
										{% if result_form  %}
											<main class="col">
												<div id="map_enterprise"></div>
											</main>
										{% endif %}
										<aside class="col-12 col-md-4 p-0 ">
											<nav class="navbar navbar-expand navbar-dark  flex-md-column  align-items-start">

												<ul class="flex-md-column flex-row navbar-nav w-100 justify-content-between">
													<li class="nav-item">
														<a class="nav-link pl-0" href="#">Menu 1</a>
														<div class="card-body">
															{% if result_form  %}
																<ul class="list-group">
																	{% for result in result_form %}
																		<li class="list-group-item my-3" data-geo="[{{ result.latitude }},{{ result.longitude }}]">
																			<strong id="business_name">{{ result.BusinessName }}</strong>
																			<br>
																			{{ result.address }}
																			<br>
																			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewbox="0 0 16 16">
																				<path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"/>
																				<path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
																			</svg>
																			{{ result.zipcode }}
																			{{ result.city }}
																			<br>
																			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewbox="0 0 16 16">
																				<path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
																			</svg>
																			{{ result.contactMail }}
																		</li>
																	{% endfor %}
																</ul>
															{% else %}
																<ul class="list-group">
																	<p>Pas d'entreprises trouvées.</p>
																</ul>
															{% endif %}
														</div>
														<!-- Insérez ici le reste de votre menu -->
													</li>
												</ul>

											</nav>
										</aside>
									</div>
								</div>
							</div>
						{% endif %}

					</div>
				</div>
			</div>
		</div>


	</main>


{% endblock %}
{% block javascripts %}
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
	{{ encore_entry_script_tags('map') }}

	{# 	<script src="{{ asset('js/map.js') }}"></script> #}
{% endblock %}

templates/enterprise/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil entreprise{% endblock %}

{% block body %}
<main>
        <section class="py-5 text-center container mt-">
            <div class="d-flex py-lg-5">
                <div class="mx-auto">
                    <h1 class="fw-bold text-start">Mon profil</h1>                    
                </div>
            </div>
        </section>    

        <ul class="navbar-nav me-4 mb-md-0">
            <li class="nav-item">
                <a class="btn btn-primary" aria-current="page" href="{{ url('enterprise_browse') }}">Retour</a>
            </li>
        </ul>

{{ form(enterprise_form) }}
                

        <ul class="navbar-nav me-4 mb-md-0">
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url('enterprise_edit', {"id": enterprise.id}) }}" title="Edit" alt="Edit">Modifier</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url('enterprise_delete', {"id": enterprise.id}) }}" title="Delete" alt="Delete">Supprimer</a>
            </li>
        </ul> 

    </main>



{% endblock %}