src/Entity/Member.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MemberRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=MemberRepository::class)
 */
class Member
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="integer")
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $job_status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $created_by;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $updated_by;

    /**
     * @ORM\ManyToMany(targetEntity=Announcement::class, mappedBy="members")
     */
    private $announcements;

    /**
     * @ORM\ManyToMany(targetEntity=SocialNetwork::class, inversedBy="members")
     */
    private $social_network;

    /**
     * @ORM\ManyToMany(targetEntity=Specialization::class, inversedBy="members")
     */
    private $specialization;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="userMember", cascade={"persist", "remove"})
     * 
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Document::class, inversedBy="member")
     */
    private $document;

    public function __construct()
    {
        $this->setUpdatedAt(new \DateTimeImmutable('now'));

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTimeImmutable('now'));
        }
        if ($this->getUpdatedAt() === null) {
            $this->setUpdatedAt(new \DateTimeImmutable('now'));
        }
        $this->announcements = new ArrayCollection();
        $this->social_network = new ArrayCollection();
        $this->specialization = new ArrayCollection();
        
    }
    public function __toString()
    {
        return $this->firstname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getJobStatus(): ?int
    {
        return $this->job_status;
    }

    public function setJobStatus(int $job_status): self
    {
        $this->job_status = $job_status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_by;
    }

    public function setCreatedBy(?string $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getUpdatedBy(): ?string
    {
        return $this->updated_by;
    }

    public function setUpdatedBy(?string $updated_by): self
    {
        $this->updated_by = $updated_by;

        return $this;
    }



    /**
     * @return Collection|SocialNetwork[]
     */
    public function getSocialNetwork(): Collection
    {
        return $this->social_network;
    }

    public function addSocialNetwork(SocialNetwork $socialNetwork): self
    {
        if (!$this->social_network->contains($socialNetwork)) {
            $this->social_network[] = $socialNetwork;
        }

        return $this;
    }

    public function removeSocialNetwork(SocialNetwork $socialNetwork): self
    {
        $this->social_network->removeElement($socialNetwork);

        return $this;
    }

    /**
     * @return Collection|Specialization[]
     */
    public function getSpecialization(): Collection
    {
        return $this->specialization;
    }

    public function addSpecialization(Specialization $specialization): self
    {
        if (!$this->specialization->contains($specialization)) {
            $this->specialization[] = $specialization;
        }

        return $this;
    }

    public function removeSpecialization(Specialization $specialization): self
    {
        $this->specialization->removeElement($specialization);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDocument(): ?Document
    {
        return $this->document;
    }

    public function setDocument(?Document $document): self
    {
        $this->document = $document;

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->addMember($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->removeElement($announcement)) {
            $announcement->removeMember($this);
        }

        return $this;
    }
}

src/Form/BackOffice/MemberType.php
<?php

namespace App\Form\BackOffice;

use App\Entity\Member;
use App\Entity\Announcement;
use App\Entity\Specialization;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class MemberType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => "Prénom" ])
            ->add('lastname', TextType::class, [
                'label' => "Nom" ])
            /* ->add('slug') */
            ->add('description')
          //  ->add('picture')
            ->add('gender')
            ->add('city')
            ->add('job_status')
            ->add('announcements', EntityType::class, [
                'class' => Announcement::class,
                'multiple' => true,
                'expanded' => true,
                'choice_label' => 'title',
                'label' => "Liste des annonces postulées"

              
            ])
            ->add('specialization', EntityType::class, [
                'class' => Specialization::class,
                'multiple' => true,
                'expanded' => true,
                'choice_label' => 'name',
                'label' => "Spécialisations"
              
            ])
            /*   ->add('created_at')
            ->add('updated_at')
            ->add('created_by')
            ->add('updated_by')
            ->add('announcements')
            ->add('social_network')
            
            ->add('user')
            ->add('document') */;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Member::class,
        ]);
    }
}

src/Controller/BackOffice/MemberController.php
<?php

namespace App\Controller\BackOffice;

use App\Entity\Member;
use App\Form\BackOffice\MemberType;
use App\Repository\MemberRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @Route("/backoffice/membre", name="backoffice_member_")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class MemberController extends AbstractController
{

    /**
     * @Route("/", name="browse", methods={"GET"})
     */
    public function browse(MemberRepository $memberRepository): Response
    {

        return $this->render('backoffice/member/browse.html.twig', [
            'member_list' => $memberRepository->findAll(),
            'controller_name' => 'BackOffice/MemberController'
        ]);
    }

    /**
     * @Route("/{id}/read", name="read", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function read(Request $request, Member $member): Response
    {

        $memberForm = $this->createForm(MemberType::class, $member, [
            'disabled' => 'disabled'
        ]);



        // on fournit ce formulaire à notre vue
        return $this->render('backoffice/member/read.html.twig', [
            'form' => $memberForm->createView(),
            'member' => $member,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET", "POST"}, requirements={"id"="\d+"})
     */
    public function edit(Request $request, Member $member): Response
    {


        // $member->getAnnouncements(); //get the annoucements of the member
        $memberForm = $this->createForm(MemberType::class, $member);


        $memberForm->handleRequest($request);

        if ($memberForm->isSubmitted() && $memberForm->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            // Permet de sauvegarder les annonces des membres
            foreach ($member->getAnnouncements() as $announce) {
                $announce->addMember($member);
            }

            
            $entityManager->flush();

            $this->addFlash('success', "Le membre {$member->getFirstname()} {$member->getLastname()} à été modifié");

            return $this->redirectToRoute('backoffice_member_browse');
        }


        return $this->render('backoffice/member/add.html.twig', [
            'form' => $memberForm->createView(),
            'member' => $member,
            'page' => 'edit',
        ]);
    }
    /**
     * @Route("/add", name="add", methods={"GET", "POST"})
     */
    public function add(Request $request, SluggerInterface $slugger): Response
    {
        $member = new Member();


        $memberForm = $this->createForm(MemberType::class, $member);


        $memberForm->handleRequest($request);


        if ($memberForm->isSubmitted() && $memberForm->isValid()) {

            $member->setSlug(strtolower($slugger->slug($member->getFirstname() . '-' . $member->getLastname())));

            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($member);
            $entityManager->flush();


            $this->addFlash('success', "Member {$member->getFirstname()} {$member->getLastname()} created successfully");


            return $this->redirectToRoute('backoffice_member_browse');
        }


        return $this->render('backoffice/member/add.html.twig', [
            'form' => $memberForm->createView(),
            'page' => 'create',
        ]);
    }

    /**
     * @Route("/delete/{id}", name="delete", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function delete(Member $member, EntityManagerInterface $entityManager): Response
    {
        $this->addFlash('success', "Member {$member->getId()} deleted");

        $entityManager->remove($member);
        $entityManager->flush();

        return $this->redirectToRoute('backoffice_member_browse');
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Member;
use DateTimeImmutable;
use App\Form\MemberType;
use App\Entity\Enterprise;
use App\Form\EnterpriseType;
use App\Form\BackOffice\UserType;
use App\Repository\MemberRepository;
use App\Repository\EnterpriseRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/profil", name="profile_")
 */
class ProfileController extends AbstractController
{
    /**
     * @Route("/entreprise/", name="enterprise", methods={"GET"})
     */
    public function enterpriseHome(Security $security): Response
    {
        /**
         * @var User
         */
        $userEnterprise =  $security->getUser();
        $userEnterprise->getUserEnterprise()->getBusinessName();

        return $this->render('profile/enterprise/home.html.twig', [
            'enterprise' => $userEnterprise,
        ]);
    }
    /**
     * @Route("/societe/", name="company", methods={"GET"})
     */
    public function companyHome(Security $security): Response
    {
        /**
         * @var User
         */
        $userCompany =  $security->getUser();
        $userCompany->getUserCompany()->getBusinessName();

        return $this->render('profile/company/home.html.twig', [
            'compagny' => $userCompany,
        ]);
    }

    /**
     * @Route("/membre", name="member", methods={"GET"})
     */
    public function memberHome(Security $security): Response
    {
        /**
         * @var User
         */
        $userMember = $security->getUser();
        $userMember->getUserMember()->getFirstName();
        return $this->render('profile/member/home.html.twig', [
            'member' => $userMember,
        ]);
    }
}

templates/profile/member/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if page == 'create' %}
    New Character
    {% else %}
    Character {{ member.firstName }} {{ member.lastName }}
    {% endif %}
{% endblock %}



{% block body %}
<div class="container mt-6">

<h1> 
    {% if page == 'create' %}
        Nouveau Membre
    {% else %}
        Modifier {{ member.firstName }} {{ member.lastName }}
    {% endif %}
</h1>
<div class="text-end">
</div>

<ul class="navbar-nav me-4 mb-md-0">
    <li class="nav-item">
        <a class="btn btn-primary" aria-current="page" href="{{ url('member_browse') }}">Retour</a>
    </li>
</ul> 

{{ form_start(member_form) }}


    {{ form_errors(member_form) }}
    {{ form_row(member_form.firstname) }}
    {{ form_row(member_form.lastname) }}
    {{ form_row(member_form.gender) }}
    {{ form_row(member_form.city) }}
    {{ form_row(member_form.job_status) }}        
    {{ form_row(member_form.description) }}
    
    

   <button type="submit" class="btn btn-primary mt-4">
		Modifier
    </button>

{{ form_end(member_form) }} 

</div>
{% endblock %}

templates/profile/member/editSpecializations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace membre{% endblock %}

{% block body %}

<main>
	<div class="container">
		<div class="card card-primary card-outline">
			<div class="card-header">
				<h3 class="card-title text-center">
					<i class="fas fa-edit"></i>
					Bienvenue dans votre espace Membre
				</h3>
			</div>
			<div class="card" style="padding-bottom: 1rem;">
				
				<div class="row">
					<div class="col-5 col-sm-3 text-center">
						<h4 class="px-0 py-2 text-left fw-bold pe-5">Mon compte</h4>
							<h6 class="px-0 py-2 text-center pe-5">{{ app.user.userMember.firstname ~ " " ~ app.user.userMember.lastname }}</h6>
							<div class="nav flex-column nav-pills pe-5 mx-auto" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
								<a class="nav-link" id="vert-tabs-connexion-tab" data-toggle="pill" href="#vert-tabs-connexion" role="tab" aria-controls="vert-tabs-connexion" aria-selected="false">Infos de connexion</a>
								<a class="nav-link" id="vert-tabs-coordinate-tab" data-toggle="pill" href="#vert-tabs-coordinate" role="tab" aria-controls="vert-tabs-coordinate" aria-selected="false">Mes Informations personnelles</a>
								<a class="nav-link active" id="vert-tabs-specialization-tab" data-toggle="pill" href="#vert-tabs-specialization" role="tab" aria-controls="vert-tabs-specialization" aria-selected="false">Mes spécialisations</a>
								<a class="nav-link" id="vert-tabs-delete-tab" data-toggle="pill" href="#vert-tabs-delete" role="tab" aria-controls="vert-tabs-delete" aria-selected="true">Supprimer mon compte</a>
								<br><h4 class="px-0 py-2 text-left fw-bold">Mes annonces</h4>
								<a class="nav-link" id="vert-tabs-announcement-tab" data-toggle="pill" href="#vert-tabs-announcement" role="tab" aria-controls="vert-tabs-announcement" aria-selected="true">Gérer mes annonces</a>
							</div>
						</div>
						<div class="col-7 col-sm-9">
							<div class="tab-content" id="vert-tabs-tabContent">
				<!--		<div class="tab-pane text-left fade active show" id="vert-tabs-connexion" role="tabpanel" aria-labelledby="vert-tabs-connexion-tab">
									<h3 class="mb-5"><strong>Mes informations de connexion</strong></h3>
									<div class="mb-3 d-flex flex-column"><strong>Email :</strong>
										<p>{{ app.user }}</p>
									</div>
									<div class="mb-3 d-flex flex-column"><strong>Password :</strong>
										<p>*********</p>
									</div>
									<a class="btn btn-primary" href="{{ url('member_edit_connexion') }}" title="EditConnexion" alt="Edit">Modifier</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-coordinate" role="tabpanel" aria-labelledby="vert-tabs-coordinate-tab">
									<h3 class="mb-5"><strong>Mes informations personnelles</strong></h3>
									<p><strong>Prénom: </strong><br>{{ app.user.userMember.firstname }}</p>
									<p><strong>Nom : </strong><br>{{ app.user.userMember.lastname }}</p>
									<p><strong>Description : </strong><br>{{ app.user.userMember.description }}</p>
									<p><strong>Ville : </strong><br>{{ app.user.userMember.city }}</p>
									<p><strong>Genre : </strong><br>
										{% if app.user.userMember.gender == "1" %}
											Homme
										{% else %}
											Femme
										{% endif %}
									</p>
									<p><strong>Status : </strong><br>
									{% if app.user.userMember.jobStatus == "1" %}
											Actuellement en poste
										{% else %}
											En recherche d'emploi
										{% endif %}
									</p>

									<a class="btn btn-primary" href="{{ url('member_edit_perso') }}" title="personal information" alt="Edit">Modifier</a>
								</div> 
								<div class="tab-pane fade active" id="vert-tabs-specialization" role="tabpanel" aria-labelledby="vert-tabs-specialization-tab"> -->
									<h3 class="mb-5"><strong>Mes spécialisations</strong></h3><br>
									<a class="btn btn-primary" aria-current="page" href="{{ url('profile_member') }}">Retour</a>
									{{ form(specialization_form) }}
								</div>
								<div class="tab-pane fade" id="vert-tabs-delete" role="tabpanel" aria-labelledby="vert-tabs-delete-tab">
									<h3 class="mb-5"><strong>Supprimer mon compte</strong></h3>
									<p>Cette action supprimera définitivement votre compte.</p>
									<a class="btn btn-primary" href="{{ url('member_delete') }}" title="DeleteAccount" alt="Delete">Suppression du compte</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-announcement" role="tabpanel" aria-labelledby="vert-tabs-announcement-tab">
									<h3 class="mb-5">Mes annonces</h3><br>
									{# {% if  app.user.userMember.announcement != null %}
										{% for annonce in app.user.userMember.announcement %}
											<li><a href="{{ path('announcement_read', {"id": annonce.id}) }}">{{annonce.title}}</a></li>
											
											<ul class="d-flex flex-row navbar-nav me-4 mb-md-0">
												<li class="nav-item">
														<a class="btn btn-primary" aria-current="page" href="{{ path('announcement_edit', {"id" : annonce.id}) }}">Modifier</a>
												</li>
												<li class="nav-item">
														<a class="btn btn-primary" aria-current="page" href="{{ path('announcement_delete', {"id" : annonce.id}) }}">Supprimer</a>
												</li>
											</ul> 

										{% endfor %}
									{% else %}
										<p>Aucune annonce n'a été créée pour le moment.</p>	 
									{% endif %} #}
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
			<!-- /.card -->

		</div>
	</div>
</main>
{% endblock %}

templates/profile/member/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace membre{% endblock %}

{% block body %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success" role="alert">{{ message }}</div>
	{% endfor %}

<main>
	<div class="container mt-5">
		<div class="card card-primary card-outline">
			<div class="card-header">
				<h3 class="card-title text-center">
					<i class="fas fa-edit"></i>
					Bienvenue dans votre espace Membre
				</h3>
			</div>
			<div class="card" style="padding-bottom: 1rem;">
				
				<div class="row">
					<div class="col-5 col-sm-3 text-center">
						<h4 class="px-0 py-2 text-left fw-bold pe-5">Mon compte</h4>
							<h6 class="px-0 py-2 text-center pe-5">{{ app.user.userMember.firstname ~ " " ~ app.user.userMember.lastname }}</h6>
							<div class="nav flex-column nav-pills pe-5 mx-auto" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
								<a class="nav-link active" id="vert-tabs-connexion-tab" data-toggle="pill" href="#vert-tabs-connexion" role="tab" aria-controls="vert-tabs-connexion" aria-selected="false">Infos de connexion</a>
								<a class="nav-link" id="vert-tabs-coordinate-tab" data-toggle="pill" href="#vert-tabs-coordinate" role="tab" aria-controls="vert-tabs-coordinate" aria-selected="false">Mes Informations personnelles</a>
								<a class="nav-link" id="vert-tabs-specialization-tab" data-toggle="pill" href="#vert-tabs-specialization" role="tab" aria-controls="vert-tabs-specialization" aria-selected="false">Mes spécialisations</a>
								<a class="nav-link" id="vert-tabs-delete-tab" data-toggle="pill" href="#vert-tabs-delete" role="tab" aria-controls="vert-tabs-delete" aria-selected="true">Supprimer mon compte</a>
								<br><h4 class="px-0 py-2 text-left fw-bold">Mes annonces</h4>
								<a class="nav-link" id="vert-tabs-announcement-tab" data-toggle="pill" href="#vert-tabs-announcement" role="tab" aria-controls="vert-tabs-announcement" aria-selected="true">Gérer mes annonces</a>
							</div>
						</div>
						<div class="col-7 col-sm-9">
							<div class="tab-content" id="vert-tabs-tabContent">
								<div class="tab-pane text-left fade active show" id="vert-tabs-connexion" role="tabpanel" aria-labelledby="vert-tabs-connexion-tab">
									<h3 class="mb-5"><strong>Mes informations de connexion</strong></h3>
									<div class="mb-3 d-flex flex-column"><strong>Email :</strong>
										<p>{{ app.user }}</p>
									</div>
									<div class="mb-3 d-flex flex-column"><strong>Password :</strong>
										<p>*********</p>
									</div>
									<a class="btn btn-primary" href="{{ url('member_edit_connexion') }}" title="EditConnexion" alt="Edit">Modifier</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-coordinate" role="tabpanel" aria-labelledby="vert-tabs-coordinate-tab">
									<h3 class="mb-5"><strong>Mes informations personnelles</strong></h3>
									<p><strong>Prénom: </strong><br>{{ app.user.userMember.firstname }}</p>
									<p><strong>Nom : </strong><br>{{ app.user.userMember.lastname }}</p>
									<p><strong>Description : </strong><br>{{ app.user.userMember.description }}</p>
									<p><strong>Ville : </strong><br>{{ app.user.userMember.city }}</p>
									<p><strong>Genre : </strong><br>
										{% if app.user.userMember.gender == "1" %}
											Homme
										{% else %}
											Femme
										{% endif %}
									</p>
									<p><strong>Status : </strong><br>
									{% if app.user.userMember.jobStatus == "1" %}
											Actuellement en poste
										{% else %}
											En recherche d'emploi
										{% endif %}
									</p>

									<a class="btn btn-primary" href="{{ url('member_edit_perso', {'_fragment': 'vert-tabs-coordinate'}) }}" title="personal information" alt="Edit">Modifier</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-specialization" role="tabpanel" aria-labelledby="vert-tabs-specialization-tab">
									<h3 class="mb-5"><strong>Mes spécialisations</strong></h3><br>
									{% if  app.user.userMember.specialization is not empty %}
										{% for specialization in app.user.userMember.specialization %}	
											<li>{{specialization.name}}</li>
										{% endfor %}
										<a class="btn btn-primary my-5" href="{{ url('member_edit_specialization', {'_fragment': 'vert-tabs-specialization'}) }}" title="add specialization" alt="Edit">Modifier mes spécialisations</a>
									{% else %}
										<p>Aucune spécialisation trouvée.</p>	 
									{% endif %}
									
									<a class="btn btn-primary my-5" href="{{ url('member_edit_specialization', {'_fragment': 'vert-tabs-specialization'}) }}" title="add specialization" alt="Edit">Ajouter des spécialisations</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-delete" role="tabpanel" aria-labelledby="vert-tabs-delete-tab">
									<h3 class="mb-5"><strong>Supprimer mon compte</strong></h3>
									<p>Cette action supprimera définitivement votre compte.</p>
									<a class="btn btn-primary" href="{{ url('member_delete') }}" title="DeleteAccount" alt="Delete">Suppression du compte</a>
								</div>
								<div class="tab-pane fade" id="vert-tabs-announcement" role="tabpanel" aria-labelledby="vert-tabs-announcement-tab">
									<h3 class="mb-5">Mes annonces</h3><br>
								{# {{ dump(app.user.userMember) }} #}
									 {% if  app.user.userMember.announcements is not empty %}
										{% for annonce in app.user.userMember.announcements %}
											<li><a href="{{ path('announcement_read', {"id": annonce.id}) }}">{{annonce.title}}</a></li>
											
										{% endfor %}
									{% else %}
										<p>Vous n'avez postulé à aucune annonces.</p>	 
									{% endif %} 
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
			<!-- /.card -->

		</div>
	</div>
</main>
{% endblock %}

templates/profile/member/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition du profil Membre{% endblock %}

{% block body %}
<main>
        <section class="py-5 text-center container mt-">
            <div class="d-flex py-lg-5">
                <div class="mx-auto">
                    <h1 class="fw-bold text-start">Mon profil</h1>                    
                </div>
            </div>
        </section>    

        <ul class="navbar-nav me-4 mb-md-0">
            <li class="nav-item">
                <a class="btn btn-primary" aria-current="page" href="{{ url('member_browse') }}">Retour</a>
            </li>
        </ul>

{{ form(member_form) }}
                

        <ul class="navbar-nav me-4 mb-md-0">
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url('member_edit', {"id": member.id}) }}" title="Edit" alt="Edit">Modifier</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url('member_delete', {"id": member.id}) }}" title="Delete" alt="Delete">Supprimer</a>
            </li>
        </ul> 

    </main>



{% endblock %}